pipeline {
    agent {
        docker {
            image 'python:3.12.4-alpine'
        }
    }
    stages {
        stage('Check Python') {
            steps {
                sh 'python --version'
            }
        }
    }
}
